# Generated by Django 4.2 on 2023-06-19 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dip_Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=200)),
                ('objectives', models.CharField(max_length=200)),
                ('target_participants', models.CharField(max_length=200, null=True)),
                ('coverage', models.CharField(max_length=200, null=True)),
                ('duration', models.CharField(max_length=200, null=True)),
                ('dip_remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('am_remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('is_dip_submited', models.BooleanField(default=False)),
                ('is_dip_approved', models.BooleanField(default=False)),
                ('is_dip_rejected', models.BooleanField(default=False)),
                ('is_am_submited', models.BooleanField(default=False)),
                ('is_am_approved', models.BooleanField(default=False)),
                ('is_am_rejected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
        ),
        migrations.CreateModel(
            name='Weekly_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('unit', models.IntegerField(blank=True, null=True)),
                ('approved_budget', models.IntegerField(blank=True, null=True)),
                ('cumulative_progress', models.CharField(blank=True, max_length=500, null=True)),
                ('cumulative_utilisation', models.CharField(blank=True, max_length=500, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPP.dip_activities')),
            ],
        ),
        migrations.CreateModel(
            name='Week_two_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, choices=[('1', 'Completed'), ('2', 'In-Progress'), ('3', 'Not-Started')], max_length=10, null=True)),
                ('weekly_Report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPP.weekly_report')),
            ],
        ),
        migrations.CreateModel(
            name='Week_three_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, choices=[('1', 'Completed'), ('2', 'In-Progress'), ('3', 'Not-Started')], max_length=10, null=True)),
                ('weekly_Report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPP.weekly_report')),
            ],
        ),
        migrations.CreateModel(
            name='Week_one_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, choices=[('1', 'Completed'), ('2', 'In-Progress'), ('3', 'Not-Started')], max_length=10, null=True)),
                ('weekly_Report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPP.weekly_report')),
            ],
        ),
        migrations.CreateModel(
            name='Week_four_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, choices=[('1', 'Completed'), ('2', 'In-Progress'), ('3', 'Not-Started')], max_length=10, null=True)),
                ('weekly_Report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPP.weekly_report')),
            ],
        ),
        migrations.CreateModel(
            name='Week_five_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, choices=[('1', 'Completed'), ('2', 'In-Progress'), ('3', 'Not-Started')], max_length=10, null=True)),
                ('weekly_Report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPP.weekly_report')),
            ],
        ),
        migrations.CreateModel(
            name='Project_DIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('budget', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('period', models.IntegerField()),
                ('donor_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPP.project_category')),
            ],
        ),
        migrations.CreateModel(
            name='Monthly_Project_Clearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_month', models.CharField(choices=[('1', 'JANUARY'), ('2', 'FEBRUARY'), ('3', 'MARCH'), ('4', 'APRIL'), ('5', 'MAY'), ('6', 'JUNE'), ('7', 'JULY'), ('8', 'AUGUST'), ('9', 'SEPTEMBER'), ('10', 'OCTOBER'), ('11', 'NOVEMBER'), ('12', 'DECEMBER')], max_length=15)),
                ('monthly_project_plan', models.BooleanField()),
                ('individual_plan_updated', models.BooleanField()),
                ('individual_worksheet_updated', models.BooleanField()),
                ('monthly_progress_report_updated', models.BooleanField()),
                ('outstation_report', models.BooleanField()),
                ('monthly_budget_submited', models.BooleanField()),
                ('settlement_completed', models.BooleanField()),
                ('project_staff_completed_required_project_compliances', models.BooleanField()),
                ('release_Salary_project_staff_recommend', models.BooleanField()),
                ('staff_reason', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPP.project_dip')),
            ],
        ),
        migrations.CreateModel(
            name='Month_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('strategy', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('no_Of_Participants', models.CharField(max_length=200)),
                ('location_Of_Activity', models.CharField(max_length=200)),
                ('main_Responsibility', models.CharField(max_length=200)),
                ('supportive_Responsibility', models.CharField(max_length=200)),
                ('result_Expected', models.CharField(max_length=200)),
                ('plan_remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('report_remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('achievements', models.CharField(blank=True, max_length=200, null=True)),
                ('highlights', models.CharField(blank=True, max_length=200, null=True)),
                ('backlog_justification', models.CharField(blank=True, max_length=200, null=True)),
                ('is_plan_submited', models.BooleanField(default=False)),
                ('is_plan_approved', models.BooleanField(default=False)),
                ('is_plan_rejected', models.BooleanField(default=False)),
                ('is_report_submited', models.BooleanField(default=False)),
                ('is_report_approved', models.BooleanField(default=False)),
                ('is_report_rejected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPP.dip_activities')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('venue', models.CharField(max_length=200)),
                ('no_of_participants', models.CharField(max_length=200)),
                ('main_objective', models.CharField(max_length=200)),
                ('key_event', models.CharField(max_length=200)),
                ('total_budget', models.CharField(max_length=100)),
                ('point_person', models.CharField(max_length=200)),
                ('support_persons', models.CharField(max_length=200)),
                ('any_imp_point', models.CharField(max_length=200, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('is_submited', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPP.project_dip')),
            ],
        ),
        migrations.CreateModel(
            name='Dip_Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(max_length=200)),
                ('project_activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPP.dip_activities')),
            ],
        ),
        migrations.CreateModel(
            name='Dip_mov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mov', models.CharField(max_length=200)),
                ('project_activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPP.dip_activities')),
            ],
        ),
        migrations.CreateModel(
            name='Dip_Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(max_length=200)),
                ('project_activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPP.dip_activities')),
            ],
        ),
        migrations.CreateModel(
            name='Dip_expected_out_come',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_out_come', models.CharField(max_length=200)),
                ('project_activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPP.dip_activities')),
            ],
        ),
        migrations.CreateModel(
            name='Dip_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPP.project_dip')),
            ],
        ),
        migrations.AddField(
            model_name='dip_activities',
            name='project_detail_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPP.dip_details'),
        ),
        migrations.CreateModel(
            name='Activity_timeframe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('m1', models.BooleanField()),
                ('m2', models.BooleanField()),
                ('m3', models.BooleanField()),
                ('m4', models.BooleanField()),
                ('m5', models.BooleanField()),
                ('m6', models.BooleanField()),
                ('m7', models.BooleanField()),
                ('m8', models.BooleanField()),
                ('m9', models.BooleanField()),
                ('m10', models.BooleanField()),
                ('m11', models.BooleanField()),
                ('m12', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPP.dip_activities')),
            ],
        ),
        migrations.CreateModel(
            name='Activity_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPP.dip_activities')),
            ],
        ),
    ]
