# Generated by Django 4.2 on 2023-05-25 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dip_Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=200)),
                ('objectives', models.CharField(max_length=200)),
                ('target_participants', models.CharField(max_length=200, null=True)),
                ('coverage', models.CharField(max_length=200, null=True)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=200, null=True)),
                ('stakeholders', models.TextField(blank=True, max_length=1000, null=True)),
                ('no_Of_Participants', models.IntegerField(blank=True, null=True)),
                ('location_Of_Activity', models.CharField(blank=True, max_length=200, null=True)),
                ('main_Responsibility', models.CharField(blank=True, max_length=200, null=True)),
                ('supportive_Responsibility', models.CharField(blank=True, max_length=200, null=True)),
                ('result_Expected', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=200)),
                ('no_of_participants', models.CharField(max_length=200)),
                ('main_objective', models.CharField(max_length=200)),
                ('key_event1', models.CharField(max_length=20)),
                ('key_event2', models.CharField(max_length=20)),
                ('key_event3', models.CharField(max_length=20)),
                ('key_event4', models.CharField(max_length=20)),
                ('key_event5', models.CharField(max_length=20)),
                ('total_budget', models.CharField(max_length=20)),
                ('point_person', models.CharField(max_length=20)),
                ('support_persons', models.CharField(max_length=20)),
                ('any_imp_point', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
        ),
        migrations.CreateModel(
            name='Monthly_Activity_Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=200)),
                ('project', models.CharField(max_length=200)),
                ('m_activites', models.CharField(max_length=200)),
                ('no_of_unit', models.IntegerField()),
                ('week_1_progress', models.CharField(max_length=200)),
                ('week_2_progress', models.CharField(max_length=200)),
                ('week_3_progress', models.CharField(max_length=200)),
                ('week_4_progress', models.CharField(max_length=200)),
                ('cumulative_progress', models.CharField(max_length=200)),
                ('remark_if_any', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_code', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('programme', models.CharField(max_length=200)),
                ('month', models.CharField(max_length=200)),
                ('head_expenditure', models.CharField(max_length=200)),
                ('amount_requested_previous_month', models.IntegerField()),
                ('amount_requested_current_month', models.IntegerField()),
                ('amount_sanctioned', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
        ),
        migrations.CreateModel(
            name='Project_DIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('budget', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('period', models.IntegerField()),
                ('donor_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPP.project_category')),
            ],
        ),
        migrations.CreateModel(
            name='Month_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('Select', 'Select'), ('January', 'Jan'), ('February', 'Feb'), ('March', 'Mar'), ('April', 'Apr'), ('May', 'May'), ('June', 'Jun'), ('July', 'Jul'), ('August', 'Aug'), ('September', 'Sep'), ('October', 'Oct'), ('November', 'Nov'), ('December', 'Dec')], default='Select', max_length=25)),
                ('component', models.CharField(max_length=200)),
                ('activities', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('stakeholders', models.TextField(max_length=1000)),
                ('no_Of_Participants', models.CharField(max_length=200)),
                ('location_Of_Activity', models.CharField(max_length=200)),
                ('main_Responsibility', models.CharField(max_length=200)),
                ('supportive_Responsibility', models.CharField(max_length=200)),
                ('result_Expected', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPP.project_dip')),
            ],
        ),
        migrations.CreateModel(
            name='Dip_Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(max_length=200)),
                ('project_activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPP.dip_activities')),
            ],
        ),
        migrations.CreateModel(
            name='Dip_mov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mov', models.CharField(max_length=200)),
                ('project_activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPP.dip_activities')),
            ],
        ),
        migrations.CreateModel(
            name='Dip_Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(max_length=200)),
                ('project_activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPP.dip_activities')),
            ],
        ),
        migrations.CreateModel(
            name='Dip_expected_out_come',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_out_come', models.CharField(max_length=200)),
                ('project_activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPP.dip_activities')),
            ],
        ),
        migrations.CreateModel(
            name='Dip_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPP.project_dip')),
            ],
        ),
        migrations.AddField(
            model_name='dip_activities',
            name='project_detail_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPP.dip_details'),
        ),
        migrations.CreateModel(
            name='Annual_budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_organization', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=200)),
                ('date_of_budget', models.DateField()),
                ('local_currency', models.CharField(max_length=100)),
                ('exchange_rate', models.CharField(max_length=100)),
                ('date_approved', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('project_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPP.project_dip')),
            ],
        ),
        migrations.CreateModel(
            name='Activity_timeframe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('m1', models.BooleanField()),
                ('m2', models.BooleanField()),
                ('m3', models.BooleanField()),
                ('m4', models.BooleanField()),
                ('m5', models.BooleanField()),
                ('m6', models.BooleanField()),
                ('m7', models.BooleanField()),
                ('m8', models.BooleanField()),
                ('m9', models.BooleanField()),
                ('m10', models.BooleanField()),
                ('m11', models.BooleanField()),
                ('m12', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('activity_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myAPP.dip_activities')),
            ],
        ),
        migrations.CreateModel(
            name='Activity_Matrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPP.project_dip')),
            ],
        ),
        migrations.CreateModel(
            name='Activity_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPP.dip_activities')),
            ],
        ),
    ]
