# Generated by Django 4.2 on 2023-05-28 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_plan',
            old_name='key_event1',
            new_name='key_event',
        ),
        migrations.RemoveField(
            model_name='event_plan',
            name='key_event2',
        ),
        migrations.RemoveField(
            model_name='event_plan',
            name='key_event3',
        ),
        migrations.RemoveField(
            model_name='event_plan',
            name='key_event4',
        ),
        migrations.RemoveField(
            model_name='event_plan',
            name='key_event5',
        ),
        migrations.AddField(
            model_name='event_plan',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event_plan',
            name='project_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myAPP.project_dip'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_plan',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='activity_timeframe',
            name='activity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPP.dip_activities'),
        ),
    ]
