# Generated by Django 4.2 on 2023-05-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0002_rename_key_event1_event_plan_key_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_plan',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event_plan',
            name='start_date',
            field=models.DateField(),
        ),
    ]
