# Generated by Django 4.2 on 2023-08-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0002_alter_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthly_staff_clearance',
            name='any_other',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='monthly_staff_clearance',
            name='case_study',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthly_staff_clearance',
            name='event_report',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthly_staff_clearance',
            name='outstation_report',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
