# Generated by Django 4.2 on 2023-05-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0003_alter_event_plan_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_plan',
            name='any_imp_point',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event_plan',
            name='key_event',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event_plan',
            name='point_person',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event_plan',
            name='support_persons',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event_plan',
            name='total_budget',
            field=models.CharField(max_length=100),
        ),
    ]
