# Generated by Django 4.2 on 2023-05-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0004_alter_event_plan_any_imp_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_plan',
            name='any_imp_point',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
