# Generated by Django 4.2 on 2023-05-30 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0005_alter_event_plan_any_imp_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='month_plan',
            old_name='activities',
            new_name='strategy',
        ),
        migrations.RemoveField(
            model_name='dip_activities',
            name='actual_date',
        ),
        migrations.RemoveField(
            model_name='dip_activities',
            name='expected_date',
        ),
        migrations.RemoveField(
            model_name='dip_activities',
            name='location_Of_Activity',
        ),
        migrations.RemoveField(
            model_name='dip_activities',
            name='main_Responsibility',
        ),
        migrations.RemoveField(
            model_name='dip_activities',
            name='no_Of_Participants',
        ),
        migrations.RemoveField(
            model_name='dip_activities',
            name='result_Expected',
        ),
        migrations.RemoveField(
            model_name='dip_activities',
            name='stakeholders',
        ),
        migrations.RemoveField(
            model_name='dip_activities',
            name='supportive_Responsibility',
        ),
        migrations.RemoveField(
            model_name='month_plan',
            name='component',
        ),
        migrations.RemoveField(
            model_name='month_plan',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='month_plan',
            name='stakeholders',
        ),
        migrations.AddField(
            model_name='month_plan',
            name='activity_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myAPP.dip_activities'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dip_activities',
            name='duration',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='month_plan',
            name='month',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Activity_Matrix',
        ),
    ]
