# Generated by Django 4.2 on 2023-05-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0006_rename_activities_month_plan_strategy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='month_plan',
            name='year',
            field=models.IntegerField(default=2023),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='month_plan',
            name='month',
            field=models.IntegerField(),
        ),
    ]
