# Generated by Django 4.2 on 2023-06-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0007_month_plan_year_alter_month_plan_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='dip_activities',
            name='is_approved',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dip_activities',
            name='is_submited',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
