# Generated by Django 4.2 on 2023-06-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0009_dip_activities_is_rejected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dip_activities',
            old_name='is_approved',
            new_name='is_am_approved',
        ),
        migrations.RenameField(
            model_name='dip_activities',
            old_name='is_rejected',
            new_name='is_am_rejected',
        ),
        migrations.RenameField(
            model_name='dip_activities',
            old_name='is_submited',
            new_name='is_am_submited',
        ),
        migrations.AddField(
            model_name='dip_activities',
            name='is_dip_approved',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dip_activities',
            name='is_dip_rejected',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dip_activities',
            name='is_dip_submited',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
