# Generated by Django 4.2 on 2023-06-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0010_rename_is_approved_dip_activities_is_am_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='month_plan',
            name='is_approved',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='month_plan',
            name='is_rejected',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='month_plan',
            name='is_submited',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
