# Generated by Django 4.2 on 2023-06-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0011_month_plan_is_approved_month_plan_is_rejected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month_plan',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='month_plan',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='month_plan',
            name='is_submited',
            field=models.BooleanField(default=False),
        ),
    ]
