# Generated by Django 4.2 on 2023-06-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0012_alter_month_plan_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_plan',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event_plan',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event_plan',
            name='is_submited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dip_activities',
            name='is_am_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dip_activities',
            name='is_am_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dip_activities',
            name='is_am_submited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dip_activities',
            name='is_dip_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dip_activities',
            name='is_dip_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dip_activities',
            name='is_dip_submited',
            field=models.BooleanField(default=False),
        ),
    ]
