# Generated by Django 4.2 on 2023-06-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0013_event_plan_is_approved_event_plan_is_rejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_plan',
            name='remarks',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
