# Generated by Django 4.2 on 2023-06-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0014_event_plan_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_plan',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
