# Generated by Django 4.2 on 2023-06-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0016_dip_activities_am_remarks_dip_activities_dip_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='month_plan',
            name='achievements',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='month_plan',
            name='backlog_justification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='month_plan',
            name='highlights',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
