# Generated by Django 4.2 on 2023-06-13 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0017_month_plan_achievements_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Monthly_Activity_Tracker',
        ),
    ]
