# Generated by Django 4.2 on 2023-06-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0018_delete_monthly_activity_tracker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='month_plan',
            old_name='remarks',
            new_name='plan_remarks',
        ),
        migrations.AddField(
            model_name='month_plan',
            name='report_remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
