# Generated by Django 4.2 on 2023-06-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0019_rename_remarks_month_plan_plan_remarks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='month_plan',
            old_name='is_approved',
            new_name='is_plan_approved',
        ),
        migrations.RenameField(
            model_name='month_plan',
            old_name='is_rejected',
            new_name='is_plan_rejected',
        ),
        migrations.RenameField(
            model_name='month_plan',
            old_name='is_submited',
            new_name='is_plan_submited',
        ),
        migrations.AddField(
            model_name='month_plan',
            name='is_report_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='month_plan',
            name='is_report_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='month_plan',
            name='is_report_submited',
            field=models.BooleanField(default=False),
        ),
    ]
