# Generated by Django 4.2 on 2023-06-14 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0020_rename_is_approved_month_plan_is_plan_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekly_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('unit', models.IntegerField(blank=True, null=True)),
                ('approved_budget', models.IntegerField(blank=True, null=True)),
                ('w1', models.CharField(blank=True, max_length=500, null=True)),
                ('w2', models.CharField(blank=True, max_length=500, null=True)),
                ('w3', models.CharField(blank=True, max_length=500, null=True)),
                ('w4', models.CharField(blank=True, max_length=500, null=True)),
                ('w5', models.CharField(blank=True, max_length=500, null=True)),
                ('cumulative_progress', models.CharField(blank=True, max_length=500, null=True)),
                ('cumulative_utilisation', models.CharField(blank=True, max_length=500, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('is_submited', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPP.dip_activities')),
            ],
        ),
    ]
