# Generated by Django 4.2 on 2023-06-15 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0021_weekly_plan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Weekly_Plan',
            new_name='Weekly_Report',
        ),
    ]
