# Generated by Django 4.2 on 2023-06-15 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0022_rename_weekly_plan_weekly_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekly_report',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='weekly_report',
            name='is_rejected',
        ),
        migrations.RemoveField(
            model_name='weekly_report',
            name='is_submited',
        ),
    ]
