# Generated by Django 4.2 on 2023-06-16 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0023_remove_weekly_report_is_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week_five_Report',
            fields=[
                ('weekly_Report_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myAPP.weekly_report')),
                ('report', models.CharField(blank=True, max_length=500, null=True)),
                ('is_green', models.BooleanField(default=False)),
                ('is_yellow', models.BooleanField(default=False)),
                ('is_red', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Week_four_Report',
            fields=[
                ('weekly_Report_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myAPP.weekly_report')),
                ('report', models.CharField(blank=True, max_length=500, null=True)),
                ('is_green', models.BooleanField(default=False)),
                ('is_yellow', models.BooleanField(default=False)),
                ('is_red', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Week_one_Report',
            fields=[
                ('weekly_Report_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myAPP.weekly_report')),
                ('report', models.CharField(blank=True, max_length=500, null=True)),
                ('is_green', models.BooleanField(default=False)),
                ('is_yellow', models.BooleanField(default=False)),
                ('is_red', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Week_three_Report',
            fields=[
                ('weekly_Report_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myAPP.weekly_report')),
                ('report', models.CharField(blank=True, max_length=500, null=True)),
                ('is_green', models.BooleanField(default=False)),
                ('is_yellow', models.BooleanField(default=False)),
                ('is_red', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Week_two_Report',
            fields=[
                ('weekly_Report_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myAPP.weekly_report')),
                ('report', models.CharField(blank=True, max_length=500, null=True)),
                ('is_green', models.BooleanField(default=False)),
                ('is_yellow', models.BooleanField(default=False)),
                ('is_red', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='weekly_report',
            name='w1',
        ),
    ]
