# Generated by Django 4.2 on 2023-06-16 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0024_week_five_report_week_four_report_week_one_report_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekly_report',
            name='w2',
        ),
        migrations.RemoveField(
            model_name='weekly_report',
            name='w3',
        ),
        migrations.RemoveField(
            model_name='weekly_report',
            name='w4',
        ),
        migrations.RemoveField(
            model_name='weekly_report',
            name='w5',
        ),
    ]
