# Generated by Django 4.2 on 2023-06-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0025_remove_weekly_report_w2_remove_weekly_report_w3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week_one_report',
            name='is_green',
        ),
        migrations.RemoveField(
            model_name='week_one_report',
            name='is_red',
        ),
        migrations.RemoveField(
            model_name='week_one_report',
            name='is_yellow',
        ),
        migrations.AddField(
            model_name='week_one_report',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Completed'), ('2', 'In-PROGRESS'), ('3', 'NOT-STARTED')], max_length=10, null=True),
        ),
    ]
