# Generated by Django 4.2 on 2023-06-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0026_remove_week_one_report_is_green_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week_five_report',
            name='is_green',
        ),
        migrations.RemoveField(
            model_name='week_five_report',
            name='is_red',
        ),
        migrations.RemoveField(
            model_name='week_five_report',
            name='is_yellow',
        ),
        migrations.RemoveField(
            model_name='week_four_report',
            name='is_green',
        ),
        migrations.RemoveField(
            model_name='week_four_report',
            name='is_red',
        ),
        migrations.RemoveField(
            model_name='week_four_report',
            name='is_yellow',
        ),
        migrations.RemoveField(
            model_name='week_three_report',
            name='is_green',
        ),
        migrations.RemoveField(
            model_name='week_three_report',
            name='is_red',
        ),
        migrations.RemoveField(
            model_name='week_three_report',
            name='is_yellow',
        ),
        migrations.RemoveField(
            model_name='week_two_report',
            name='is_green',
        ),
        migrations.RemoveField(
            model_name='week_two_report',
            name='is_red',
        ),
        migrations.RemoveField(
            model_name='week_two_report',
            name='is_yellow',
        ),
        migrations.AddField(
            model_name='week_five_report',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Completed'), ('2', 'In-PROGRESS'), ('3', 'NOT-STARTED')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='week_four_report',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Completed'), ('2', 'In-PROGRESS'), ('3', 'NOT-STARTED')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='week_three_report',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Completed'), ('2', 'In-PROGRESS'), ('3', 'NOT-STARTED')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='week_two_report',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Completed'), ('2', 'In-PROGRESS'), ('3', 'NOT-STARTED')], max_length=10, null=True),
        ),
    ]
