# Generated by Django 4.2 on 2023-06-17 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0027_remove_week_five_report_is_green_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='week_five_report',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='week_four_report',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='week_one_report',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='week_three_report',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='week_two_report',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='week_five_report',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Completed'), ('2', 'In-PROGRESS'), ('3', 'Not-Started')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='week_five_report',
            name='weekly_Report_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPP.weekly_report'),
        ),
        migrations.AlterField(
            model_name='week_four_report',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Completed'), ('2', 'In-PROGRESS'), ('3', 'Not-Started')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='week_four_report',
            name='weekly_Report_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPP.weekly_report'),
        ),
        migrations.AlterField(
            model_name='week_one_report',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Completed'), ('2', 'In-PROGRESS'), ('3', 'Not-Started')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='week_one_report',
            name='weekly_Report_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPP.weekly_report'),
        ),
        migrations.AlterField(
            model_name='week_three_report',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Completed'), ('2', 'In-PROGRESS'), ('3', 'Not-Started')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='week_three_report',
            name='weekly_Report_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPP.weekly_report'),
        ),
        migrations.AlterField(
            model_name='week_two_report',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Completed'), ('2', 'In-PROGRESS'), ('3', 'Not-Started')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='week_two_report',
            name='weekly_Report_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPP.weekly_report'),
        ),
    ]
