# Generated by Django 4.2 on 2023-06-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0028_week_five_report_id_week_four_report_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekly_report',
            name='w1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='weekly_report',
            name='w2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='weekly_report',
            name='w3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='weekly_report',
            name='w4',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='weekly_report',
            name='w5',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
