# Generated by Django 4.2 on 2023-06-17 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0029_weekly_report_w1_weekly_report_w2_weekly_report_w3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monthly_Project_Clearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_month', models.CharField(max_length=500)),
                ('monthly_project_plan', models.BooleanField()),
                ('individual_plan_updated', models.BooleanField()),
                ('individual_worksheet_updated', models.BooleanField()),
                ('monthly_progress_report_updated', models.BooleanField()),
                ('outstation_report', models.BooleanField()),
                ('monthly_budget_submited', models.BooleanField()),
                ('settlement_completed', models.BooleanField()),
                ('project_staff_completed_required_project_compliances', models.BooleanField()),
                ('release_Salary_project_staff_recommend', models.BooleanField()),
                ('staff_reason', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPP.project_dip')),
            ],
        ),
    ]
