# Generated by Django 4.2 on 2023-06-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0030_monthly_project_clearance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annual_budget',
            name='project_number',
        ),
        migrations.DeleteModel(
            name='MonthlyBudget',
        ),
        migrations.RemoveField(
            model_name='weekly_report',
            name='w1',
        ),
        migrations.RemoveField(
            model_name='weekly_report',
            name='w2',
        ),
        migrations.RemoveField(
            model_name='weekly_report',
            name='w3',
        ),
        migrations.RemoveField(
            model_name='weekly_report',
            name='w4',
        ),
        migrations.RemoveField(
            model_name='weekly_report',
            name='w5',
        ),
        migrations.AlterField(
            model_name='monthly_project_clearance',
            name='reporting_month',
            field=models.CharField(choices=[('1', 'JANUARY'), ('2', 'FEBRUARY'), ('3', 'MARCH'), ('4', 'APRIL'), ('5', 'MAY'), ('6', 'JUNE'), ('7', 'JULY'), ('8', 'AUGUST'), ('9', 'SEPTEMBER'), ('10', 'OCTOBER'), ('11', 'NOVEMBER'), ('12', 'DECEMBER')], max_length=15),
        ),
        migrations.AlterField(
            model_name='week_five_report',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Completed'), ('2', 'In-Progress'), ('3', 'Not-Started')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='week_four_report',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Completed'), ('2', 'In-Progress'), ('3', 'Not-Started')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='week_one_report',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Completed'), ('2', 'In-Progress'), ('3', 'Not-Started')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='week_three_report',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Completed'), ('2', 'In-Progress'), ('3', 'Not-Started')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='week_two_report',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Completed'), ('2', 'In-Progress'), ('3', 'Not-Started')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Annual_budget',
        ),
    ]
