# Generated by Django 4.2 on 2024-03-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0005_activity_timeframe_tracking_year_month_plan_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_statement',
            name='is_approvedby_ceo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leave_statement',
            name='is_approvedby_hr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leave_statement',
            name='is_rejectedby_ceo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leave_statement',
            name='is_rejectedby_hr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthly_staff_clearance',
            name='is_approvedby_ceo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthly_staff_clearance',
            name='is_approvedby_hr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthly_staff_clearance',
            name='is_rejectedby_ceo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthly_staff_clearance',
            name='is_rejectedby_hr',
            field=models.BooleanField(default=False),
        ),
    ]
