# Generated by Django 4.2 on 2024-04-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0006_leave_statement_is_approvedby_ceo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dip_activities',
            name='target',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
